[package]
name = "dogstatsd-utils"
version = "0.1.0"
edition = "2021"


[dependencies]
zstd = "0.12.4"
byteorder = "1.4.3"
mime = "0.3.17"
new_mime_guess = "4.0.1"
prost = "0.11.9"
bytes = "1.0.1"
indicatif = "0.16.0"
clap = { version = "4.3.23", features = ["derive"] }

[build-dependencies]
prost-build = "0.11.9"
